### PR TITLE
Add linter

### PR DESCRIPTION
**Pull request by lepture**
Added `flake8` and `mypy`. There are many issues found my `mypy`.

### CODE REVIEW

**Comment by lepture** [comment]
@Viicos Can you help me with the mypy configuration.

**Comment by Viicos** [comment]
Would you like mypy to suceed first (by turning off some switches), so that we can gradually improve typing?

**Comment by lepture** [comment]
@Viicos sure. If you can join the discord sever, we can discuss about the typing on discord.

**Comment by lepture** [comment]
I'll merge the code at first. Need to create a `wip-mypy` branch.

**Pull request merged**
